name: Strapi Documentation Style Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'docusaurus/docs/**/*.md'
      - 'docusaurus/docs/**/*.mdx'
  
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to validate'
        required: true
        type: string
      target_files:
        description: 'Specific files to validate (optional - leave empty to validate all changed files in the PR)'
        required: false
        type: string

jobs:
  validate-documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PR info and checkout PR branch
        if: github.event.inputs.pr_number
        run: |
          # Get PR information
          PR_INFO=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                         -H "Accept: application/vnd.github.v3+json" \
                         "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.inputs.pr_number }}")
          
          # Extract branch name and head SHA
          BRANCH_NAME=$(echo "$PR_INFO" | jq -r '.head.ref')
          HEAD_SHA=$(echo "$PR_INFO" | jq -r '.head.sha')
          
          echo "PR #${{ github.event.inputs.pr_number }} branch: $BRANCH_NAME"
          echo "HEAD SHA: $HEAD_SHA"
          
          # Checkout the PR branch
          git fetch origin "$BRANCH_NAME"
          git checkout "$HEAD_SHA"
          
          echo "Successfully checked out PR branch"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'docusaurus/yarn.lock'

      - name: Install dependencies
        run: |
          cd docusaurus
          yarn add --dev js-yaml glob

      - name: Run Strapi 12 Rules validation
        id: validation
        run: |
          cd docusaurus
          if [ -n "${{ github.event.inputs.target_files }}" ]; then
            echo "Validating specific files: ${{ github.event.inputs.target_files }}"
            node scripts/style-validation/validate-content-style.js --verbose ${{ github.event.inputs.target_files }}
          else
            echo "Validating all documentation files"
            echo "=== Debug: Searching for new-file.md everywhere ==="
            find .. -name "new-file.md" -type f 2>/dev/null || echo "new-file.md not found anywhere"
            
            echo "=== Debug: Files changed in this PR ==="
            git diff --name-only HEAD~1 | grep -E '\.(md|mdx)$' || echo "No .md/.mdx files in recent commits"
            
            echo "=== Debug: Testing with a known file ==="
            if [ -f "docs/whats-new.md" ]; then
              echo "Testing with docs/whats-new.md:"
              node scripts/style-validation/validate-content-style.js --verbose docs/whats-new.md
            else
              echo "Even docs/whats-new.md not found!"
            fi
          fi
        continue-on-error: true

      - name: Comment PR with results
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Get inputs safely
            const prNumber = '${{ github.event.inputs.pr_number }}' || '';
            const eventName = '${{ github.event_name }}';
            
            try {
              // Read validation results
              const resultsPath = 'docusaurus/style-check-results.json';
              
              if (!fs.existsSync(resultsPath)) {
                console.log('No results file found, validation may have failed');
                
                // Only try to comment if we're in a PR context or manual run with PR number
                if (eventName === 'pull_request') {
                  await github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: '## ❌ Documentation Style Review\n\n' +
                          'Validation script failed to run. Please check the GitHub Action logs.\n\n' +
                          'This might be due to missing files or configuration issues.'
                  });
                } else if (prNumber) {
                  await github.rest.issues.createComment({
                    issue_number: parseInt(prNumber),
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: '## ❌ Documentation Style Review\n\n' +
                          'Validation script failed to run. Please check the GitHub Action logs.\n\n' +
                          'This might be due to missing files or configuration issues.'
                  });
                } else {
                  console.log('No results file found and no PR to comment on. Manual run completed.');
                }
                return;
              }

              const results = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
              
              // Generate comment
              let comment = '## 🎯 Strapi Documentation Style Review\n\n';
              comment += `*Based on Strapi's 12 Rules of Technical Writing*\n\n`;
              
              // Summary
              comment += '### 📊 Summary\n';
              comment += `- **Files checked:** ${results.summary.filesProcessed}\n`;
              comment += `- **Total issues:** ${results.summary.totalIssues}\n`;
              comment += `- **Critical errors:** ${results.issues.errors.length} 🚨\n`;
              comment += `- **Warnings:** ${results.issues.warnings.length} ⚠️\n`;
              comment += `- **Suggestions:** ${results.issues.suggestions.length} 💡\n\n`;
              
              if (results.summary.totalIssues === 0) {
                comment += '🎉 **Perfect!** Your documentation follows all 12 rules of technical writing.\n\n';
              } else {
                // Show critical errors
                if (results.issues.errors.length > 0) {
                  comment += '### 🚨 Critical Issues (must fix)\n\n';
                  results.issues.errors.slice(0, 5).forEach(error => {
                    const fileName = error.file.replace(/^.*\/docs\//, 'docs/');
                    comment += `**${fileName}:${error.line}**\n`;
                    comment += `- ${error.message}\n`;
                    if (error.suggestion) {
                      comment += `- 💡 *${error.suggestion}*\n`;
                    }
                    comment += '\n';
                  });
                  
                  if (results.issues.errors.length > 5) {
                    comment += `*... and ${results.issues.errors.length - 5} more critical issues*\n\n`;
                  }
                }
                
                // Show some warnings
                if (results.issues.warnings.length > 0) {
                  comment += '### ⚠️ Warnings (should address)\n\n';
                  results.issues.warnings.slice(0, 3).forEach(warning => {
                    const fileName = warning.file.replace(/^.*\/docs\//, 'docs/');
                    comment += `**${fileName}:${warning.line}** - ${warning.message}\n`;
                  });
                  
                  if (results.issues.warnings.length > 3) {
                    comment += `\n*... and ${results.issues.warnings.length - 3} more warnings*\n`;
                  }
                  comment += '\n';
                }
                
                // Show some suggestions
                if (results.issues.suggestions.length > 0) {
                  comment += '### 💡 Suggestions (improvements)\n\n';
                  results.issues.suggestions.slice(0, 2).forEach(suggestion => {
                    const fileName = suggestion.file.replace(/^.*\/docs\//, 'docs/');
                    comment += `**${fileName}:${suggestion.line}** - ${suggestion.message}\n`;
                  });
                  
                  if (results.issues.suggestions.length > 2) {
                    comment += `\n*... and ${results.issues.suggestions.length - 2} more suggestions*\n`;
                  }
                  comment += '\n';
                }
              }
              
              // Add footer
              comment += '---\n';
              comment += '*🤖 Automated review based on [Strapi\'s 12 Rules of Technical Writing](https://strapi.notion.site/12-Rules-of-Technical-Writing)*\n';
              
              // Add trigger info for manual runs
              if (eventName === 'workflow_dispatch') {
                comment += `*🔧 Manually triggered${prNumber ? ` for PR #${prNumber}` : ''}*\n\n`;
              }
              
              // Post comment
              if (eventName === 'pull_request') {
                // Normal PR comment
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: comment
                });
              } else if (prNumber) {
                // Manual run with PR number
                await github.rest.issues.createComment({
                  issue_number: parseInt(prNumber),
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: comment
                });
              } else {
                // Manual run without PR - just log
                console.log('Manual validation completed');
                console.log(comment);
              }
              
              // Set step output for potential failure
              if (results.issues.errors.length > 0) {
                core.setFailed(`Found ${results.issues.errors.length} critical errors that must be fixed.`);
              }
              
            } catch (error) {
              console.error('Error processing results:', error);
              
              // Only try to comment if we're in a PR context or manual run with PR number
              if (eventName === 'pull_request') {
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '## ❌ Documentation Style Review Failed\n\n' +
                        'There was an error running the style validation. Please check the GitHub Action logs.\n\n' +
                        `Error: ${error.message}`
                });
              } else if (prNumber) {
                await github.rest.issues.createComment({
                  issue_number: parseInt(prNumber),
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: '## ❌ Documentation Style Review Failed\n\n' +
                        'There was an error running the style validation. Please check the GitHub Action logs.\n\n' +
                        `Error: ${error.message}`
                });
              } else {
                console.log(`Manual validation failed: ${error.message}`);
              }
            }
